---
apiVersion: v1
kind: Namespace
metadata:
  name: teama-etcds
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: etcd-binding
  namespace: teama-etcds
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: etcd-role
subjects:
- kind: ServiceAccount
  name: etcd-operator-sa
  namespace: etcd-operator1
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: etcd-role
  namespace: teama-etcds
rules:
- apiGroups:
  - etcd.database.coreos.com
  resources:
  - etcdclusters
  - etcdbackups
  - etcdrestores
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  verbs:
  - "*"
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - "*"
# The following permissions can be removed if not using S3 backup and TLS
- apiGroups:
  - ""
  resources: 
  - secrets
  verbs:
  - get
---
apiVersion: etcd.database.coreos.com/v1beta2
kind: EtcdCluster
metadata:
  name: etcd-in-teama
  namespace: teama-etcds
  annotations:
    etcd.database.coreos.com/scope: clusterwide
spec:
  size: 3
  version: "3.2.13"