---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rbac-proxy-tester
  namespace: default





# ---
# apiVersion: rbac.authorization.k8s.io/v1beta1
# kind: ClusterRole
# metadata:
#   name: rbac-proxy-tester
# rules:
# - apiGroups:
#   - "*"
#   resources:
#   - "*"
#   verbs:
#   - list # not list and watch so that proxy doesnt accidently rely on this
#   - create
#   - update
#   - delete
# ---
# apiVersion: rbac.authorization.k8s.io/v1beta1
# kind: ClusterRoleBinding
# metadata:
#   name: rbac-proxy-tester
# roleRef:
#   apiGroup: rbac.authorization.k8s.io
#   kind: ClusterRole
#   name: rbac-proxy-tester
# subjects:
# - kind: ServiceAccount
#   name: rbac-proxy-tester
#   namespace: default



---
apiVersion: v1
kind: Namespace
metadata:
  name: rbac-proxy-test-ns1
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: rbac-proxy-tester
  namespace: rbac-proxy-test-ns1
rules:
- apiGroups:
  - "*"
  resources:
  - "*"
  verbs:
  - "*"
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: rbac-proxy-tester
  namespace: rbac-proxy-test-ns1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rbac-proxy-tester
subjects:
- kind: ServiceAccount
  name: rbac-proxy-tester
  namespace: default





---
apiVersion: v1
kind: Namespace
metadata:
  name: rbac-proxy-test-ns2
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: rbac-proxy-tester
  namespace: rbac-proxy-test-ns2
rules:
- apiGroups:
  - "*"
  resources:
  - "*"
  verbs:
  - "*"
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: rbac-proxy-tester
  namespace: rbac-proxy-test-ns2
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rbac-proxy-tester
subjects:
- kind: ServiceAccount
  name: rbac-proxy-tester
  namespace: default




---
apiVersion: v1
kind: Namespace
metadata:
  name: rbac-proxy-test-ns3
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: rbac-proxy-tester
  namespace: rbac-proxy-test-ns3
rules:
- apiGroups:
  - "*"
  resources:
  - "*"
  verbs:
  - "*"
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: rbac-proxy-tester
  namespace: rbac-proxy-test-ns3
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rbac-proxy-tester
subjects:
- kind: ServiceAccount
  name: rbac-proxy-tester
  namespace: default

