apiVersion: v1
kind: Namespace
metadata:
  name: rbac-proxy
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: rbac-proxy
rules:
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  verbs:
  - list
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: rbac-proxy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rbac-proxy
subjects:
- kind: ServiceAccount
  name: rbac-proxy
  namespace: rbac-proxy
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rbac-proxy
  namespace: rbac-proxy
---
apiVersion: v1
kind: Service
metadata:
  name: rbac-proxy
  namespace: rbac-proxy
spec:
  ports:
  - port: 443
    targetPort: 443
  selector:
    kube-rbac-proxy.cppforlife.com/proxy: ""
