apiVersion: certificates.k8s.io/v1beta1
kind: CertificateSigningRequest
metadata:
  name: rbac-proxy
spec:
  groups:
  - system:authenticated
  request: ((tls_csr))
  usages:
  - digital signature
  - key encipherment
  - server auth
